name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Pedagogy
      working-directory: ./pedagogika
      run: make xelatex & make booklet
    - name: Cleaning trash
      working-directory: ./pedagogika
      run: make clean
