name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure
      
    - name: Pedagogika
      working-directory: ./pedagogika
      run: make xelatex & make booklet
    - name: Čištění
      working-directory: ./pedagogika
      run: make clean
